[package]
name = "alloy-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Command-line interface, REPL, package manager, and language server protocol (LSP) daemon for the Alloy runtime."

[lints]
workspace = true

[dependencies]
alloy-rt = { path = "../alloy-rt", version = "0.2.0" }
alloy-vm = { path = "../alloy-vm", version = "0.2.0" }
alloy-core = { package = "alloy-runtime-core", path = "../alloy-core", version = "0.2.0" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true

[[bin]]
name = "alloy"
path = "src/main.rs"
